import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Calender",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-indigo-50 flex flex-col h-screen`}
      >
        <Toaster position="top-center" />
        {/* Main content area - scrollable, takes full height minus navbar height */}
        <div className="flex-1 overflow-y-auto pb-16">{children}</div>
        {/* Navbar - fixed at bottom */}
        <div className="fixed bottom-0 left-0 right-0 h-16 bg-white border-t border-gray-200 z-50">
          <Navbar />
        </div>
      </body>
    </html>
  );
}
